<a href="https://colab.research.google.com/github/Prayag79/Deep-learning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [245]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


In [246]:
#Tensors
scalar = torch.tensor(9)
scalar

tensor(9)

In [247]:
scalar.ndim

0

In [248]:
#tensor to int
scalar.item()

9

In [249]:
#vector
vector = torch.tensor([7,9])
vector.ndim


1

In [250]:
vector.shape

torch.Size([2])

In [251]:
MATRIX = torch.tensor([[7,7,9],
                       [8,9,1],
                       [1,1,1]])
MATRIX.ndim

2

In [252]:
MATRIX.shape

torch.Size([3, 3])

In [253]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [1,2,3],
                        [1,2,3]]])
TENSOR.ndim


3

In [254]:
#look at the shape (inresting)
TENSOR.shape
#one 3 by 3 tensor

torch.Size([1, 3, 3])

In [255]:
TENSOR1 = torch.tensor([[[1,2],
                        [1,2],
                        [1,2]]])
TENSOR1.shape

torch.Size([1, 3, 2])

In [256]:
#random TENSORS
#size(3, 4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.5352, 0.9802, 0.7321, 0.3491],
        [0.2936, 0.7444, 0.9339, 0.4873],
        [0.7142, 0.7505, 0.2988, 0.2044]])

In [257]:
#creating a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (224,224,3))#height width colour channels ( rgb )
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [258]:
# zeros and one
zeros = torch.zeros(3,4)
zeros

#very usefull for base net

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [259]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [260]:
ones.dtype#data type


torch.float32

In [261]:
# range of tensors and tensors_like
#1.
#arange takes (start,end,steps) ; excluding end ( similar to string slicing )
a = torch.arange(0,10,1)
a
#a.dtype

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [262]:
#2.tensor like

ten_zeros = torch.zeros_like(input=a)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [263]:
#tensors datatype
a=torch.tensor([.1,.2,.3],
               dtype = None,
               device = None,#useful when you change devices ( gpu , etc)
               requires_grad=False) # if to track a gradients or not
a,a.dtype #default dtype is float even if explicitly mentioned as none(but not in case of mentioning as int , check !)

(tensor([0.1000, 0.2000, 0.3000]), torch.float32)

In [264]:
flt_16_tensor = a.type(torch.float16)
flt_16_tensor

# explore more from the documentation

tensor([0.1000, 0.2000, 0.3000], dtype=torch.float16)

In [265]:
(a * flt_16_tensor).dtype # does not always works , sometimes throws up an error )

torch.float32

In [266]:
b = torch.tensor([1,2,3],
                 dtype = torch.long)
(a*b).dtype

torch.float32

In [267]:
# Tensor opertions
# 1. basic algebra
# 2. linear algebra -- matrix multiplication


In [268]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [269]:
tensor*10

tensor([10, 20, 30])

In [270]:
tensor - 10

tensor([-9, -8, -7])

In [271]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [272]:
# pytorch inbuilt functions
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [273]:
#MAtrix multiplication
#1.Element wise
#2.Matrix multiplication


In [274]:
torch.matmul(tensor,tensor)

tensor(14)

In [275]:
torch.matmul(torch.rand(3,4) , torch.rand(4,10)) , torch.matmul(torch.rand(3,4) , torch.rand(4,10)).shape


(tensor([[0.8798, 1.1208, 0.9800, 0.5609, 0.7268, 0.7330, 0.6967, 0.9622, 0.8490,
          0.8276],
         [0.8155, 1.1461, 0.9884, 0.9752, 0.9628, 0.8544, 0.6340, 1.1292, 0.7847,
          0.8834],
         [1.6155, 2.2087, 1.9431, 1.4748, 1.7015, 1.5501, 1.3660, 2.0412, 1.6371,
          1.7050]]),
 torch.Size([3, 10]))

In [276]:
#Transpose
a=torch.rand(3,2)
b = torch.rand(3,2)
c=torch.mm(a,b.T)
c

tensor([[0.3702, 0.3545, 0.4393],
        [0.3331, 0.3723, 0.3823],
        [0.3773, 0.4460, 0.4272]])

In [277]:
#MAx, min , mean , sum , etc
x=torch.arange(1,101)
x


tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100])

In [278]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [279]:
torch.max(x)

tensor(100)

In [280]:
#lol it requires float32
torch.mean(x)
#torch.mean(x,dtype=torch.float32) ----> fix

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.sum(x)

In [281]:
#Argument
x[x.argmin()]


tensor(1)

In [282]:
#Reshaping , stacking , squeezing , unsqueezing

In [283]:
x=torch.arange(1,10)
x,x.shape , x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1)

In [285]:
#add extra dim
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape , x_reshaped.ndim


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]), 2)

In [286]:
#change the view
z=x.view(1,9)#changing z changes ****x**** cuz it shares memory
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [287]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim =0)
x_stacked


tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [288]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [289]:
#squeeze
torch.squeeze(x_reshaped)#remove all 1D


#The returned tensor shares the storage with the input tensor, so changing the contents of one will change the contents of the other

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [290]:
x = torch.zeros(2, 1, 2, 1, 2)
y = torch.squeeze(x) #2x2x2
y.size()

torch.Size([2, 2, 2])

In [291]:
z = y.unsqueeze(dim = 0)# adds extra 1 dim
z.shape


torch.Size([1, 2, 2, 2])

In [292]:
#permute
x = torch.rand(2,3,5)
x.size() , x.permute(2,0,1).size()

(torch.Size([2, 3, 5]), torch.Size([5, 2, 3]))

In [296]:
#indexing
x = torch.arange(1,10).reshape(1,3,3)
x

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3)

In [297]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [298]:
#mid bracket
x[0][0] # or x[0,0]

tensor([1, 2, 3])

In [299]:
#last dim
x[0][0][0]

tensor(1)

In [300]:
x[0][2][2]

tensor(9)

In [306]:
import numpy as np

In [ ]:
# torch.from_numpy(ndarray)
# torch.Tensor.numpy()


In [327]:
array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array)#.type to change dtype
array , tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [335]:
#array += 1
#tensor # tensor gets updated as they shares memory

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [337]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproduciblity

In [350]:
import torch
r1 = torch.rand(3,4)
r2 = torch.rand(3,4)

r1 , r2 , print(r1==r2)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


(tensor([[0.4776, 0.9511, 0.2743, 0.2513],
         [0.8284, 0.4615, 0.5465, 0.0608],
         [0.1474, 0.1837, 0.7576, 0.0268]]),
 tensor([[0.6825, 0.6150, 0.4481, 0.8354],
         [0.9825, 0.1245, 0.3621, 0.5501],
         [0.1370, 0.8976, 0.9238, 0.2353]]),
 None)

In [360]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
d = torch.rand(3,4)
c,d,print(c==d)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 None)